// packages/shared/src/schemas/redirect.schema.ts
import { z } from "zod";

export const redirectEntityTypeEnum = z.enum([
  "BLOG_POST",
  "CASE_STUDY",
  "BLOG_CATEGORY",
  "STATIC_PAGE",
  "CUSTOM",
]);

export const createRedirectSchema = z.object({
  sourcePath: z
    .string()
    .min(1, "Source path is required")
    .transform((val) => val.trim()),
  targetPath: z
    .string()
    .min(1, "Target destination is required")
    .transform((val) => val.trim()),
  statusCode: z.coerce
    .number()
    .int()
    .refine((val) => [301, 302, 307, 308].includes(val), {
      message: "Status code must be 301 (Permanent), 302 (Found), 307 (Temporary), or 308 (Permanent)",
    })
    .default(301),
  entityType: redirectEntityTypeEnum.default("CUSTOM"),
  entityId: z.string().uuid().nullable().optional(),
  isActive: z.boolean().default(true),
  notes: z.string().max(500, "Notes cannot exceed 500 characters").nullable().optional(),
});

export const updateRedirectSchema = z.object({
  sourcePath: z
    .string()
    .min(1, "Source path cannot be empty")
    .transform((val) => val.trim())
    .optional(),
  targetPath: z
    .string()
    .min(1, "Target destination cannot be empty")
    .transform((val) => val.trim())
    .optional(),
  statusCode: z.coerce
    .number()
    .int()
    .refine((val) => [301, 302, 307, 308].includes(val), {
      message: "Status code must be 301, 302, 307, or 308",
    })
    .optional(),
  entityType: redirectEntityTypeEnum.optional(),
  entityId: z.string().uuid().nullable().optional(),
  isActive: z.boolean().optional(),
  notes: z.string().max(500).nullable().optional(),
});

export const queryRedirectsSchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
  search: z.string().optional(),
  entityType: z
    .enum(["ALL", "BLOG_POST", "CASE_STUDY", "BLOG_CATEGORY", "STATIC_PAGE", "CUSTOM"])
    .optional(),
  statusCode: z.coerce.number().int().optional(),
  isActive: z.enum(["true", "false", "all"]).optional(),
  autoGenerated: z.enum(["true", "false", "all"]).optional(),
  sortBy: z
    .enum(["createdAt", "updatedAt", "hitCount", "lastHitAt", "sourcePath", "targetPath"])
    .default("createdAt"),
  sortOrder: z.enum(["asc", "desc"]).default("desc"),
});

export const resolveRedirectSchema = z.object({
  path: z.string().min(1, "Path parameter is required"),
});

export const bulkDeleteRedirectsSchema = z.object({
  ids: z.array(z.string().uuid()).min(1, "At least one redirect ID is required"),
});
