"use client"

import * as React from "react"
import {
  ArrowRightLeft,
  Plus,
  Search,
  RefreshCw,
  ExternalLink,
  Trash2,
  Edit2,
  Copy,
  Check,
  AlertTriangle,
  Activity,
  ShieldCheck,
  Zap,
  Globe,
  Filter,
  MoreVertical,
  Layers,
  FileCode2,
  FolderTree,
} from "lucide-react"

import type {
  RedirectDTO,
  RedirectStatsDTO,
  RedirectEntityType,
  CreateRedirectDTO,
  UpdateRedirectDTO,
} from "@workspace/shared"
import { redirectApi } from "@/lib/api/redirect.api"
import { Badge } from "@workspace/ui/components/badge"
import { Button } from "@workspace/ui/components/button"
import { Input } from "@workspace/ui/components/input"
import { Switch } from "@workspace/ui/components/switch"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@workspace/ui/components/card"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@workspace/ui/components/dialog"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@workspace/ui/components/dropdown-menu"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@workspace/ui/components/select"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@workspace/ui/components/table"
import { toast } from "@workspace/ui/components/sonner"

export default function RedirectsPage() {
  const [redirects, setRedirects] = React.useState<RedirectDTO[]>([])
  const [stats, setStats] = React.useState<RedirectStatsDTO>({
    totalRedirects: 0,
    activeRedirects: 0,
    permanentCount: 0,
    temporaryCount: 0,
    autoGeneratedCount: 0,
    customCount: 0,
    totalHits: 0,
    entityBreakdown: {
      BLOG_POST: 0,
      CASE_STUDY: 0,
      BLOG_CATEGORY: 0,
      STATIC_PAGE: 0,
      CUSTOM: 0,
    },
  })
  const [isLoading, setIsLoading] = React.useState(true)
  const [isSaving, setIsSaving] = React.useState(false)

  // Filters
  const [search, setSearch] = React.useState("")
  const [entityType, setEntityType] = React.useState<string>("ALL")
  const [statusCode, setStatusCode] = React.useState<string>("ALL")
  const [isActiveFilter, setIsActiveFilter] = React.useState<string>("all")
  const [originFilter, setOriginFilter] = React.useState<string>("all")

  // Pagination
  const [page, setPage] = React.useState(1)
  const [totalPages, setTotalPages] = React.useState(1)
  const [totalCount, setTotalCount] = React.useState(0)

  // Modals
  const [isCreateOpen, setIsCreateOpen] = React.useState(false)
  const [editingRedirect, setEditingRedirect] = React.useState<RedirectDTO | null>(null)
  const [deletingId, setDeletingId] = React.useState<string | null>(null)
  const [copiedId, setCopiedId] = React.useState<string | null>(null)

  // Form states
  const [formData, setFormData] = React.useState<CreateRedirectDTO>({
    sourcePath: "",
    targetPath: "",
    statusCode: 301,
    entityType: "CUSTOM",
    isActive: true,
    notes: "",
  })

  const loadStats = React.useCallback(async () => {
    try {
      const res = await redirectApi.getStats()
      if (res.success && res.data) {
        setStats(res.data)
      }
    } catch {
      // Ignore stats error on background fetch
    }
  }, [])

  const loadRedirects = React.useCallback(async () => {
    setIsLoading(true)
    try {
      const res = await redirectApi.getRedirects({
        page,
        limit: 20,
        search: search.trim() || undefined,
        entityType: entityType === "ALL" ? undefined : (entityType as any),
        statusCode: statusCode === "ALL" ? undefined : Number(statusCode),
        isActive: isActiveFilter === "all" ? undefined : (isActiveFilter as any),
        autoGenerated: originFilter === "all" ? undefined : (originFilter as any),
        sortBy: "createdAt",
        sortOrder: "desc",
      })

      if (res.success && res.data) {
        setRedirects(res.data)
        if (res.meta?.pagination) {
          setTotalPages(res.meta.pagination.totalPages)
          setTotalCount(res.meta.pagination.total)
        }
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to load redirects")
    } finally {
      setIsLoading(false)
    }
  }, [page, search, entityType, statusCode, isActiveFilter, originFilter])

  React.useEffect(() => {
    loadStats()
  }, [loadStats])

  React.useEffect(() => {
    loadRedirects()
  }, [loadRedirects])

  const handleCopy = (path: string, id: string) => {
    navigator.clipboard.writeText(path)
    setCopiedId(id)
    setTimeout(() => setCopiedId(null), 2000)
    toast.success("Path copied to clipboard")
  }

  const handleToggleActive = async (redirect: RedirectDTO) => {
    const updatedStatus = !redirect.isActive
    try {
      const res = await redirectApi.updateRedirect(redirect.id, {
        isActive: updatedStatus,
      })
      if (res.success) {
        setRedirects((prev) =>
          prev.map((r) => (r.id === redirect.id ? { ...r, isActive: updatedStatus } : r))
        )
        toast.success(
          `Redirect ${updatedStatus ? "activated" : "deactivated"} successfully`
        )
        loadStats()
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to update redirect status")
    }
  }

  const handleCreateSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!formData.sourcePath.trim()) {
      toast.error("Source path is required")
      return
    }
    if (!formData.targetPath.trim()) {
      toast.error("Target destination is required")
      return
    }
    if (formData.sourcePath.trim() === formData.targetPath.trim()) {
      toast.error("Source path and destination cannot be identical")
      return
    }

    setIsSaving(true)
    try {
      const res = await redirectApi.createRedirect({
        ...formData,
        statusCode: Number(formData.statusCode),
      })
      if (res.success) {
        toast.success("301 Redirect rule created successfully")
        setIsCreateOpen(false)
        setFormData({
          sourcePath: "",
          targetPath: "",
          statusCode: 301,
          entityType: "CUSTOM",
          isActive: true,
          notes: "",
        })
        loadRedirects()
        loadStats()
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to create redirect")
    } finally {
      setIsSaving(false)
    }
  }

  const handleEditSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!editingRedirect) return

    setIsSaving(true)
    try {
      const res = await redirectApi.updateRedirect(editingRedirect.id, {
        sourcePath: editingRedirect.sourcePath,
        targetPath: editingRedirect.targetPath,
        statusCode: Number(editingRedirect.statusCode),
        entityType: editingRedirect.entityType,
        isActive: editingRedirect.isActive,
        notes: editingRedirect.notes,
      })
      if (res.success) {
        toast.success("Redirect rule updated successfully")
        setEditingRedirect(null)
        loadRedirects()
        loadStats()
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to update redirect")
    } finally {
      setIsSaving(false)
    }
  }

  const handleDelete = async () => {
    if (!deletingId) return
    setIsSaving(true)
    try {
      const res = await redirectApi.deleteRedirect(deletingId)
      if (res.success) {
        toast.success("Redirect rule deleted")
        setDeletingId(null)
        loadRedirects()
        loadStats()
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to delete redirect")
    } finally {
      setIsSaving(false)
    }
  }

  const getStatusBadge = (code: number) => {
    switch (code) {
      case 301:
        return (
          <Badge className="border-emerald-500/30 bg-emerald-500/10 font-mono text-xs text-emerald-400">
            301 Permanent
          </Badge>
        )
      case 308:
        return (
          <Badge className="border-teal-500/30 bg-teal-500/10 font-mono text-xs text-teal-400">
            308 Permanent
          </Badge>
        )
      case 302:
        return (
          <Badge className="border-amber-500/30 bg-amber-500/10 font-mono text-xs text-amber-400">
            302 Found
          </Badge>
        )
      case 307:
        return (
          <Badge className="border-yellow-500/30 bg-yellow-500/10 font-mono text-xs text-yellow-400">
            307 Temporary
          </Badge>
        )
      default:
        return <Badge variant="outline">{code}</Badge>
    }
  }

  const getEntityBadge = (type: RedirectEntityType) => {
    switch (type) {
      case "BLOG_POST":
        return (
          <Badge variant="outline" className="gap-1 border-blue-500/30 bg-blue-500/5 text-blue-400">
            <FileCode2 className="size-3" />
            Blog Post
          </Badge>
        )
      case "CASE_STUDY":
        return (
          <Badge variant="outline" className="gap-1 border-purple-500/30 bg-purple-500/5 text-purple-400">
            <Layers className="size-3" />
            Case Study
          </Badge>
        )
      case "BLOG_CATEGORY":
        return (
          <Badge variant="outline" className="gap-1 border-indigo-500/30 bg-indigo-500/5 text-indigo-400">
            <FolderTree className="size-3" />
            Category
          </Badge>
        )
      case "STATIC_PAGE":
        return (
          <Badge variant="outline" className="gap-1 border-cyan-500/30 bg-cyan-500/5 text-cyan-400">
            <Globe className="size-3" />
            Static Page
          </Badge>
        )
      default:
        return (
          <Badge variant="outline" className="gap-1 border-muted text-muted-foreground">
            Custom
          </Badge>
        )
    }
  }

  return (
    <div className="flex flex-1 flex-col gap-6 p-6 md:p-8">
      {/* Header */}
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-bold tracking-tight md:text-3xl">
              URL Redirects & SEO
            </h1>
            <Badge variant="outline" className="border-primary/30 text-primary">
              Live Routing
            </Badge>
          </div>
          <p className="mt-1 text-sm text-muted-foreground">
            Manage HTTP 301/308 permanent redirects, preserve backlink equity, and monitor traffic from renamed content.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              loadRedirects()
              loadStats()
            }}
            disabled={isLoading}
            className="gap-1.5"
          >
            <RefreshCw className={`size-3.5 ${isLoading ? "animate-spin" : ""}`} />
            <span>Refresh</span>
          </Button>

          <Button
            size="sm"
            onClick={() => setIsCreateOpen(true)}
            className="gap-1.5 shadow-sm"
          >
            <Plus className="size-4" />
            <span>Add Redirect</span>
          </Button>
        </div>
      </div>

      {/* KPI Stats Overview */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card className="border-border/60 bg-card/60 backdrop-blur-xs">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Total Redirects
            </CardTitle>
            <ArrowRightLeft className="size-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.totalRedirects}</div>
            <p className="mt-1 text-xs text-muted-foreground">
              <span className="text-emerald-400 font-semibold">{stats.activeRedirects} active</span> • {stats.totalRedirects - stats.activeRedirects} disabled
            </p>
          </CardContent>
        </Card>

        <Card className="border-border/60 bg-card/60 backdrop-blur-xs">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              301 Permanent (SEO)
            </CardTitle>
            <ShieldCheck className="size-4 text-emerald-400" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-emerald-400">{stats.permanentCount}</div>
            <p className="mt-1 text-xs text-muted-foreground">
              Preserving 100% PageRank link juice
            </p>
          </CardContent>
        </Card>

        <Card className="border-border/60 bg-card/60 backdrop-blur-xs">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Auto-Tracked Slugs
            </CardTitle>
            <Zap className="size-4 text-amber-400" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.autoGeneratedCount}</div>
            <p className="mt-1 text-xs text-muted-foreground">
              {stats.customCount} manual vanity / alias rules
            </p>
          </CardContent>
        </Card>

        <Card className="border-border/60 bg-card/60 backdrop-blur-xs">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Preserved Traffic Hits
            </CardTitle>
            <Activity className="size-4 text-blue-400" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-400">{stats.totalHits}</div>
            <p className="mt-1 text-xs text-muted-foreground">
              Requests rescued from 404 errors
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Filter Toolbar */}
      <Card className="border-border/60 bg-card/40">
        <CardContent className="p-4">
          <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                placeholder="Search source path, target destination, notes..."
                value={search}
                onChange={(e) => {
                  setSearch(e.target.value)
                  setPage(1)
                }}
                className="pl-9 bg-background/50"
              />
            </div>

            <div className="flex flex-wrap items-center gap-2">
              <Select
                value={entityType}
                onValueChange={(val) => {
                  setEntityType(val)
                  setPage(1)
                }}
              >
                <SelectTrigger className="w-[140px] bg-background/50 text-xs">
                  <SelectValue placeholder="Entity" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ALL">All Entities</SelectItem>
                  <SelectItem value="BLOG_POST">Blog Posts</SelectItem>
                  <SelectItem value="CASE_STUDY">Case Studies</SelectItem>
                  <SelectItem value="BLOG_CATEGORY">Categories</SelectItem>
                  <SelectItem value="STATIC_PAGE">Static Pages</SelectItem>
                  <SelectItem value="CUSTOM">Custom</SelectItem>
                </SelectContent>
              </Select>

              <Select
                value={statusCode}
                onValueChange={(val) => {
                  setStatusCode(val)
                  setPage(1)
                }}
              >
                <SelectTrigger className="w-[130px] bg-background/50 text-xs">
                  <SelectValue placeholder="Status Code" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ALL">All Codes</SelectItem>
                  <SelectItem value="301">301 Permanent</SelectItem>
                  <SelectItem value="308">308 Permanent</SelectItem>
                  <SelectItem value="302">302 Found</SelectItem>
                  <SelectItem value="307">307 Temporary</SelectItem>
                </SelectContent>
              </Select>

              <Select
                value={originFilter}
                onValueChange={(val) => {
                  setOriginFilter(val)
                  setPage(1)
                }}
              >
                <SelectTrigger className="w-[130px] bg-background/50 text-xs">
                  <SelectValue placeholder="Origin" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Origins</SelectItem>
                  <SelectItem value="true">Auto-Generated</SelectItem>
                  <SelectItem value="false">Manual Custom</SelectItem>
                </SelectContent>
              </Select>

              <Select
                value={isActiveFilter}
                onValueChange={(val) => {
                  setIsActiveFilter(val)
                  setPage(1)
                }}
              >
                <SelectTrigger className="w-[120px] bg-background/50 text-xs">
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="true">Active Only</SelectItem>
                  <SelectItem value="false">Inactive</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Main Redirects Table */}
      <Card className="border-border/60">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow className="hover:bg-transparent">
                <TableHead className="w-[280px]">Source Path (From)</TableHead>
                <TableHead className="w-[280px]">Target Destination (To)</TableHead>
                <TableHead className="w-[120px]">Status Code</TableHead>
                <TableHead className="w-[120px]">Entity</TableHead>
                <TableHead className="w-[100px]">Origin</TableHead>
                <TableHead className="w-[100px] text-center">Hits</TableHead>
                <TableHead className="w-[100px] text-center">Active</TableHead>
                <TableHead className="w-[80px] text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={8} className="h-36 text-center">
                    <div className="flex flex-col items-center justify-center gap-2 text-muted-foreground">
                      <RefreshCw className="size-5 animate-spin text-primary" />
                      <span>Loading redirect routes...</span>
                    </div>
                  </TableCell>
                </TableRow>
              ) : redirects.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={8} className="h-40 text-center">
                    <div className="flex flex-col items-center justify-center gap-2 text-muted-foreground">
                      <ArrowRightLeft className="size-8 text-muted-foreground/40" />
                      <p className="font-semibold text-foreground">No redirects found</p>
                      <p className="text-xs">
                        {search || entityType !== "ALL" || statusCode !== "ALL"
                          ? "Try clearing filters to see all redirects"
                          : "Slug updates on blog posts or case studies will automatically appear here"}
                      </p>
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => setIsCreateOpen(true)}
                        className="mt-2"
                      >
                        <Plus className="mr-1.5 size-3.5" />
                        Create First Redirect
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ) : (
                redirects.map((r) => (
                  <TableRow key={r.id} className="group">
                    {/* Source Path */}
                    <TableCell className="font-mono text-xs">
                      <div className="flex items-center gap-1.5">
                        <span className="font-semibold text-foreground truncate max-w-[220px]" title={r.sourcePath}>
                          {r.sourcePath}
                        </span>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="size-6 opacity-0 group-hover:opacity-100 transition-opacity"
                          onClick={() => handleCopy(r.sourcePath, r.id)}
                          title="Copy source path"
                        >
                          {copiedId === r.id ? (
                            <Check className="size-3 text-emerald-400" />
                          ) : (
                            <Copy className="size-3 text-muted-foreground" />
                          )}
                        </Button>
                      </div>
                      {r.notes && (
                        <p className="text-[11px] text-muted-foreground/80 truncate max-w-[240px]" title={r.notes}>
                          {r.notes}
                        </p>
                      )}
                    </TableCell>

                    {/* Target Destination */}
                    <TableCell className="font-mono text-xs">
                      <div className="flex items-center gap-1.5">
                        <span className="text-primary truncate max-w-[220px]" title={r.targetPath}>
                          {r.targetPath}
                        </span>
                        {r.targetPath.startsWith("http") && (
                          <ExternalLink className="size-3 text-muted-foreground shrink-0" />
                        )}
                      </div>
                    </TableCell>

                    {/* Status Code */}
                    <TableCell>{getStatusBadge(r.statusCode)}</TableCell>

                    {/* Entity Type */}
                    <TableCell>{getEntityBadge(r.entityType)}</TableCell>

                    {/* Origin */}
                    <TableCell>
                      {r.autoGenerated ? (
                        <Badge variant="outline" className="border-amber-500/30 text-amber-400 font-mono text-[10px]">
                          Auto
                        </Badge>
                      ) : (
                        <Badge variant="outline" className="border-muted text-muted-foreground font-mono text-[10px]">
                          Manual
                        </Badge>
                      )}
                    </TableCell>

                    {/* Hits */}
                    <TableCell className="text-center font-mono text-xs">
                      <span className="font-semibold">{r.hitCount}</span>
                      {r.lastHitAt && (
                        <span className="block text-[10px] text-muted-foreground">
                          {new Date(r.lastHitAt).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                        </span>
                      )}
                    </TableCell>

                    {/* Active Toggle */}
                    <TableCell className="text-center">
                      <Switch
                        checked={r.isActive}
                        onCheckedChange={() => handleToggleActive(r)}
                      />
                    </TableCell>

                    {/* Actions */}
                    <TableCell className="text-right">
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon" className="size-8">
                            <MoreVertical className="size-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" className="w-40">
                          <DropdownMenuLabel>Actions</DropdownMenuLabel>
                          <DropdownMenuItem
                            onClick={() => setEditingRedirect(r)}
                            className="gap-2"
                          >
                            <Edit2 className="size-3.5" />
                            <span>Edit Rule</span>
                          </DropdownMenuItem>
                          <DropdownMenuItem
                            onClick={() => handleCopy(r.sourcePath, r.id)}
                            className="gap-2"
                          >
                            <Copy className="size-3.5" />
                            <span>Copy Source</span>
                          </DropdownMenuItem>
                          <DropdownMenuSeparator />
                          <DropdownMenuItem
                            onClick={() => setDeletingId(r.id)}
                            className="gap-2 text-destructive focus:text-destructive"
                          >
                            <Trash2 className="size-3.5" />
                            <span>Delete</span>
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>

        {/* Pagination Bar */}
        {totalPages > 1 && (
          <div className="flex items-center justify-between border-t border-border px-4 py-3 text-xs text-muted-foreground">
            <span>
              Showing {redirects.length} of {totalCount} redirects
            </span>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                disabled={page <= 1 || isLoading}
              >
                Previous
              </Button>
              <span className="font-mono">
                {page} / {totalPages}
              </span>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                disabled={page >= totalPages || isLoading}
              >
                Next
              </Button>
            </div>
          </div>
        )}
      </Card>

      {/* Create Redirect Dialog */}
      <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
        <DialogContent className="sm:max-w-[520px]">
          <form onSubmit={handleCreateSubmit}>
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <ArrowRightLeft className="size-5 text-primary" />
                <span>Create URL Redirect Rule</span>
              </DialogTitle>
              <DialogDescription>
                Configure a server-side redirect to route traffic from old or alias paths directly to new destinations.
              </DialogDescription>
            </DialogHeader>

            <div className="grid gap-4 py-4">
              <div className="grid gap-1.5">
                <label className="text-xs font-semibold">Source Path (From)</label>
                <Input
                  placeholder="/blog/my-old-post-title or /old-landing"
                  value={formData.sourcePath}
                  onChange={(e) =>
                    setFormData((prev) => ({ ...prev, sourcePath: e.target.value }))
                  }
                  required
                  className="font-mono text-xs"
                />
                <p className="text-[11px] text-muted-foreground">
                  The incoming request URL path that should be intercepted.
                </p>
              </div>

              <div className="grid gap-1.5">
                <label className="text-xs font-semibold">Target Destination (To)</label>
                <Input
                  placeholder="/blog/my-new-post-title or https://external.com/page"
                  value={formData.targetPath}
                  onChange={(e) =>
                    setFormData((prev) => ({ ...prev, targetPath: e.target.value }))
                  }
                  required
                  className="font-mono text-xs"
                />
                <p className="text-[11px] text-muted-foreground">
                  The final canonical destination URL where visitors and crawlers should land.
                </p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-1.5">
                  <label className="text-xs font-semibold">HTTP Status Code</label>
                  <Select
                    value={String(formData.statusCode)}
                    onValueChange={(val) =>
                      setFormData((prev) => ({ ...prev, statusCode: Number(val) }))
                    }
                  >
                    <SelectTrigger className="text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="301">301 - Moved Permanently (SEO)</SelectItem>
                      <SelectItem value="308">308 - Permanent Redirect</SelectItem>
                      <SelectItem value="302">302 - Found (Temporary)</SelectItem>
                      <SelectItem value="307">307 - Temporary Redirect</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="grid gap-1.5">
                  <label className="text-xs font-semibold">Entity Type</label>
                  <Select
                    value={formData.entityType}
                    onValueChange={(val) =>
                      setFormData((prev) => ({ ...prev, entityType: val as any }))
                    }
                  >
                    <SelectTrigger className="text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="CUSTOM">Custom Alias</SelectItem>
                      <SelectItem value="BLOG_POST">Blog Post</SelectItem>
                      <SelectItem value="CASE_STUDY">Case Study</SelectItem>
                      <SelectItem value="BLOG_CATEGORY">Blog Category</SelectItem>
                      <SelectItem value="STATIC_PAGE">Static Page</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid gap-1.5">
                <label className="text-xs font-semibold">Notes / Rationale</label>
                <Input
                  placeholder="e.g., Migrated from old portfolio version or marketing campaign link"
                  value={formData.notes || ""}
                  onChange={(e) =>
                    setFormData((prev) => ({ ...prev, notes: e.target.value }))
                  }
                  className="text-xs"
                />
              </div>

              <div className="flex items-center justify-between rounded-lg border border-border/80 p-3">
                <div className="space-y-0.5">
                  <label className="text-xs font-semibold">Active Immediately</label>
                  <p className="text-[11px] text-muted-foreground">
                    Enable redirect routing as soon as this rule is saved.
                  </p>
                </div>
                <Switch
                  checked={formData.isActive}
                  onCheckedChange={(checked) =>
                    setFormData((prev) => ({ ...prev, isActive: checked }))
                  }
                />
              </div>
            </div>

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={() => setIsCreateOpen(false)}
                disabled={isSaving}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={isSaving}>
                {isSaving ? "Saving..." : "Create 301 Redirect"}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* Edit Redirect Dialog */}
      <Dialog
        open={Boolean(editingRedirect)}
        onOpenChange={(open) => !open && setEditingRedirect(null)}
      >
        <DialogContent className="sm:max-w-[520px]">
          {editingRedirect && (
            <form onSubmit={handleEditSubmit}>
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  <Edit2 className="size-5 text-primary" />
                  <span>Edit Redirect Rule</span>
                </DialogTitle>
                <DialogDescription>
                  Modify the source path, target destination, or HTTP status code.
                </DialogDescription>
              </DialogHeader>

              <div className="grid gap-4 py-4">
                <div className="grid gap-1.5">
                  <label className="text-xs font-semibold">Source Path</label>
                  <Input
                    value={editingRedirect.sourcePath}
                    onChange={(e) =>
                      setEditingRedirect((prev) =>
                        prev ? { ...prev, sourcePath: e.target.value } : null
                      )
                    }
                    required
                    className="font-mono text-xs"
                  />
                </div>

                <div className="grid gap-1.5">
                  <label className="text-xs font-semibold">Target Destination</label>
                  <Input
                    value={editingRedirect.targetPath}
                    onChange={(e) =>
                      setEditingRedirect((prev) =>
                        prev ? { ...prev, targetPath: e.target.value } : null
                      )
                    }
                    required
                    className="font-mono text-xs"
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="grid gap-1.5">
                    <label className="text-xs font-semibold">HTTP Status Code</label>
                    <Select
                      value={String(editingRedirect.statusCode)}
                      onValueChange={(val) =>
                        setEditingRedirect((prev) =>
                          prev ? { ...prev, statusCode: Number(val) } : null
                        )
                      }
                    >
                      <SelectTrigger className="text-xs">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="301">301 - Moved Permanently (SEO)</SelectItem>
                        <SelectItem value="308">308 - Permanent Redirect</SelectItem>
                        <SelectItem value="302">302 - Found (Temporary)</SelectItem>
                        <SelectItem value="307">307 - Temporary Redirect</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="grid gap-1.5">
                    <label className="text-xs font-semibold">Entity Type</label>
                    <Select
                      value={editingRedirect.entityType}
                      onValueChange={(val) =>
                        setEditingRedirect((prev) =>
                          prev ? { ...prev, entityType: val as any } : null
                        )
                      }
                    >
                      <SelectTrigger className="text-xs">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="CUSTOM">Custom</SelectItem>
                        <SelectItem value="BLOG_POST">Blog Post</SelectItem>
                        <SelectItem value="CASE_STUDY">Case Study</SelectItem>
                        <SelectItem value="BLOG_CATEGORY">Blog Category</SelectItem>
                        <SelectItem value="STATIC_PAGE">Static Page</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="grid gap-1.5">
                  <label className="text-xs font-semibold">Notes</label>
                  <Input
                    value={editingRedirect.notes || ""}
                    onChange={(e) =>
                      setEditingRedirect((prev) =>
                        prev ? { ...prev, notes: e.target.value } : null
                      )
                    }
                    className="text-xs"
                  />
                </div>

                <div className="flex items-center justify-between rounded-lg border border-border/80 p-3">
                  <div className="space-y-0.5">
                    <label className="text-xs font-semibold">Status Active</label>
                    <p className="text-[11px] text-muted-foreground">
                      Deactivating stops routing without deleting the record.
                    </p>
                  </div>
                  <Switch
                    checked={editingRedirect.isActive}
                    onCheckedChange={(checked) =>
                      setEditingRedirect((prev) =>
                        prev ? { ...prev, isActive: checked } : null
                      )
                    }
                  />
                </div>
              </div>

              <DialogFooter>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setEditingRedirect(null)}
                  disabled={isSaving}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isSaving}>
                  {isSaving ? "Saving..." : "Save Changes"}
                </Button>
              </DialogFooter>
            </form>
          )}
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog
        open={Boolean(deletingId)}
        onOpenChange={(open) => !open && setDeletingId(null)}
      >
        <DialogContent className="sm:max-w-[420px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-destructive">
              <AlertTriangle className="size-5" />
              <span>Delete Redirect Rule</span>
            </DialogTitle>
            <DialogDescription>
              Are you sure you want to delete this redirect rule? Visitors hitting the old path will receive a 404 Not Found error.
            </DialogDescription>
          </DialogHeader>

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setDeletingId(null)}
              disabled={isSaving}
            >
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={handleDelete}
              disabled={isSaving}
            >
              {isSaving ? "Deleting..." : "Delete Rule"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
