version: '3.8'

services:
    portfolio-frontend:
        image: fiamanillah/portfolio-frontend:latest
        build:
            context: ./portfolio-frontend # Current directory (portfolio-frontend)
        ports:
            - '3010:3010'
        env_file:
            - ./portfolio-frontend/.env.production # Or .env if you want
        restart: unless-stopped
