services:
    postgres:
        image: postgres:17
        container_name: portfolio_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: fiamanillah
            POSTGRES_PASSWORD: fiamanillah
            POSTGRES_DB: portfolio_db
        ports:
            - '5445:5432'
        volumes:
            - portfolio_postgres_data:/var/lib/postgresql/data
        networks:
            - portfolio_network

    redis:
        image: redis:7-alpine
        container_name: portfolio_redis
        restart: unless-stopped
        command: redis-server --appendonly yes
        ports:
            - '6380:6379'
        volumes:
            - portfolio_redis_data:/data
        networks:
            - portfolio_network

networks:
    portfolio_network:
        driver: bridge
        name: portfolio_network

volumes:
    portfolio_postgres_data:
        driver: local
        name: portfolio_postgres_data
    portfolio_redis_data:
        driver: local
        name: portfolio_redis_data

