services:
    postgres:
        image: postgres:17
        container_name: portfolio_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: fiamanillah
            POSTGRES_PASSWORD: fiamanillah
            POSTGRES_DB: portfolio_db
        ports:
            - '5435:5432'
        volumes:
            - portfolio_postgres_data:/var/lib/postgresql/data
        networks:
            - portfolio_network

networks:
    portfolio_network:
        driver: bridge
        name: portfolio_network

volumes:
    portfolio_postgres_data:
        driver: local
        name: portfolio_postgres_data
