// packages/shared/src/types/redirect.ts
import { z } from "zod";
import {
  redirectEntityTypeEnum,
  createRedirectSchema,
  updateRedirectSchema,
  queryRedirectsSchema,
  resolveRedirectSchema,
  bulkDeleteRedirectsSchema,
} from "../schemas/redirect.schema";

export type RedirectEntityType = z.infer<typeof redirectEntityTypeEnum>;

export interface CreateRedirectDTO {
  sourcePath: string;
  targetPath: string;
  statusCode?: number;
  entityType?: RedirectEntityType;
  entityId?: string | null;
  isActive?: boolean;
  notes?: string | null;
}

export interface UpdateRedirectDTO {
  sourcePath?: string;
  targetPath?: string;
  statusCode?: number;
  entityType?: RedirectEntityType;
  entityId?: string | null;
  isActive?: boolean;
  notes?: string | null;
}

export interface QueryRedirectsDTO {
  page?: number;
  limit?: number;
  search?: string;
  entityType?: "ALL" | RedirectEntityType;
  statusCode?: number;
  isActive?: "true" | "false" | "all";
  autoGenerated?: "true" | "false" | "all";
  sortBy?: "createdAt" | "updatedAt" | "hitCount" | "lastHitAt" | "sourcePath" | "targetPath";
  sortOrder?: "asc" | "desc";
}

export interface ResolveRedirectDTO {
  path: string;
}

export interface BulkDeleteRedirectsDTO {
  ids: string[];
}

export interface RedirectDTO {
  id: string;
  sourcePath: string;
  targetPath: string;
  statusCode: number;
  entityType: RedirectEntityType;
  entityId?: string | null;
  autoGenerated: boolean;
  isActive: boolean;
  hitCount: number;
  lastHitAt?: string | null;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ResolvedRedirectDTO {
  redirected: boolean;
  destination?: string;
  statusCode?: number;
  permanent?: boolean;
}

export interface RedirectStatsDTO {
  totalRedirects: number;
  activeRedirects: number;
  permanentCount: number; // 301 / 308
  temporaryCount: number; // 302 / 307
  autoGeneratedCount: number;
  customCount: number;
  totalHits: number;
  entityBreakdown: Record<RedirectEntityType, number>;
}
