import { ThemeProvider } from 'next-themes';
import '@/app/globals.css';
import { Oxanium } from 'next/font/google';

const oxanium = Oxanium({
    subsets: ['latin'],
    weight: ['400'], // Choose weights you need
    variable: '--font-oxanium', // Define a CSS variable for Tailwind
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`antialiased bg-background text-foreground ${oxanium.variable} font-oxanium`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
