// apps/dashboard/src/lib/api/redirect.api.ts
import { request, ApiResponse } from "./client"
import type {
  RedirectDTO,
  RedirectStatsDTO,
  CreateRedirectDTO,
  UpdateRedirectDTO,
  QueryRedirectsDTO,
} from "@workspace/shared"

export const redirectApi = {
  /**
   * Admin: List redirects with filtering, search, and pagination
   */
  async getRedirects(
    params: QueryRedirectsDTO = {}
  ): Promise<ApiResponse<RedirectDTO[]>> {
    const query = new URLSearchParams()
    if (params.page) query.append("page", String(params.page))
    if (params.limit) query.append("limit", String(params.limit))
    if (params.search) query.append("search", params.search)
    if (params.entityType) query.append("entityType", params.entityType)
    if (params.statusCode) query.append("statusCode", String(params.statusCode))
    if (params.isActive) query.append("isActive", params.isActive)
    if (params.autoGenerated) query.append("autoGenerated", params.autoGenerated)
    if (params.sortBy) query.append("sortBy", params.sortBy)
    if (params.sortOrder) query.append("sortOrder", params.sortOrder)

    const queryString = query.toString() ? `?${query.toString()}` : ""
    return request<RedirectDTO[]>(`/redirects/v1/admin${queryString}`)
  },

  /**
   * Admin: Get statistics and KPI analytics
   */
  async getStats(): Promise<ApiResponse<RedirectStatsDTO>> {
    return request<RedirectStatsDTO>("/redirects/v1/admin/stats")
  },

  /**
   * Admin: Create a manual redirect
   */
  async createRedirect(
    data: CreateRedirectDTO
  ): Promise<ApiResponse<RedirectDTO>> {
    return request<RedirectDTO>("/redirects/v1/admin", {
      method: "POST",
      body: JSON.stringify(data),
    })
  },

  /**
   * Admin: Update an existing redirect
   */
  async updateRedirect(
    id: string,
    data: UpdateRedirectDTO
  ): Promise<ApiResponse<RedirectDTO>> {
    return request<RedirectDTO>(`/redirects/v1/admin/${id}`, {
      method: "PATCH",
      body: JSON.stringify(data),
    })
  },

  /**
   * Admin: Delete a redirect rule
   */
  async deleteRedirect(id: string): Promise<ApiResponse<{ id: string }>> {
    return request<{ id: string }>(`/redirects/v1/admin/${id}`, {
      method: "DELETE",
    })
  },

  /**
   * Admin: Bulk delete redirect rules
   */
  async bulkDeleteRedirects(
    ids: string[]
  ): Promise<ApiResponse<{ count: number }>> {
    return request<{ count: number }>("/redirects/v1/admin/bulk-delete", {
      method: "POST",
      body: JSON.stringify({ ids }),
    })
  },
}
