name: Deploy

on:
    push:
        branches:
            - prod
    workflow_dispatch:

env:
    DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    VITE_BASE_API_URL: ${{ secrets.VITE_BASE_API_URL }}
    VITE_BASE_SOCKET_URL: ${{ secrets.VITE_BASE_SOCKET_URL }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.DOCKER_HUB_USERNAME }}
                  password: ${{ env.DOCKER_HUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: ./
                  file: ./Dockerfile
                  build-args: |
                      NODE_ENV=production
                      VITE_BASE_API_URL=${{ env.VITE_BASE_API_URL }}
                      VITE_BASE_SOCKET_URL=${{ env.VITE_BASE_SOCKET_URL }}
                  push: true
                  tags: |
                      ${{ env.DOCKER_HUB_USERNAME }}/portfolio-frontend:prod
                      ${{ env.DOCKER_HUB_USERNAME }}/portfolio-frontend:${{ github.sha }}
            - name: Check env
              run: |
                  echo ${{ env.DOCKER_HUB_USERNAME }}
                  echo ${{ env.DOCKER_HUB_TOKEN }}
                  echo ${{ github }}
